#!/bin/bash
# Cache regularly cloned Git repositories
# Licence: WTFPL 2.0


function error {
    local code="$1"; shift

    for message in "$@"; do echo "$message" >&2; done
    exit $code
}

function find_cache_dir {
    local cache_dir=$(git config cache.directory)
    [ -d "$cache_dir" ] || \
      error 1 "Nonexistant cache directory, please create it with 'git cache init [DIR]'"
    echo "$cache_dir"
}

function set_umask {
    local cache_dir="$1"; shift
    [[ $cache_dir ]] || cache_dir=$(find_cache_dir) || error 1
    is_system_cache "$cache_dir" && umask 002
}

#########
## MANAGE CACHE

function create_cache {
    local cache_dir="$1"
    local type="$2"

    [ "$type" ] || type=global
    if [ -z "$cache_dir" ]; then
      cache_dir=~/.cache/git-cache
      if [ -w /var/cache ]; then
        cache_dir=/var/cache/git-cache
        type=system
      fi
      if [ -w /Library/Caches ]; then
        cache_dir=/Library/Caches/git-cache
        type=system
      fi
    fi

    [[ $cache_dir =~ ^/|~ ]] || cache_dir="$PWD/$cache_dir"

    set_umask "$cache_dir"
    init_cache "$cache_dir"

    git config --${type} cache.directory $cache_dir
}

function init_cache {
    local cache_dir="$1"

    [ "$cache_dir" ] || \
      error 1 "No cache dir supplied"
    [ -d "$cache_dir" -a -f "$cache_dir/HEAD" ] && \
      error 1 "Cache directory is already initialised. You can use 'git cache delete --force' to delete it." "Cache dir = '$cache_dir'"

    mkdir -p "$cache_dir"
    ( cd "$cache_dir"
      git init --bare )

    if is_system_cache "$cache_dir"; then
      chgrp -R users "$cache_dir"
      chmod -R ug+rw "$cache_dir"
    fi
}

function delete_cache {
    local cache_dir_system
    local cache_dir_global

    cache_dir_system="$(git config --system cache.directory)"
    if [ "$cache_dir_system" ]; then
      git config --system --remove-section cache && \
        ( rm -rf "$cache_dir_system" && \
              echo "System cache directory $cache_dir_system deleted." >&2 )
    fi

    cache_dir_global="$(git config --global cache.directory)"
    if [ "$cache_dir_global" ]; then
      git config --global --remove-section cache && \
        ( rm -rf "$cache_dir_global" && \
              echo "Global user cache directory $cache_dir_global deleted." >&2 )
    fi
}

function is_system_cache {
    local cache_dir="$1"
    [[ $cache_dir ]] || error 1 "Please supply the cache-dir to check for is_system_cache()."
    [[ $cache_dir == /var/* ]] && return 0
    return 1
}

##########
## GEN

function clone_referring_cache {
    local name="$1"; shift
    local cache_dir=$(find_cache_dir)
    [ "$name" ] || \
      error 1 "Please supply the remote name to be cloned."

    local remote_url="$(find_remote_url "$name")"
    git clone --reference "$cache_dir" "$remote_url" "$@"
}

function update_cached_repos {
    local cache_dir=$(find_cache_dir)
    ( cd "$cache_dir"
      git fetch --all --prune )
}

function show_clone_command {
    local name="$1"
    local cache_dir=$(find_cache_dir)

    find_remote_url "$name" | \
      awk '{ print "git clone --reference \"" cache_dir "\" " $0 }' cache_dir="$cache_dir"
}

##########
## REMOTE

function rm_remote {
    local name="$1"
    local cache_dir=$(find_cache_dir)
    [ "$name" ] || \
      error 1 "Please supply the remote name to be removed."

    ( cd "$cache_dir"
      git remote rm "$name" )
}

function add_remote {
    local name="$1"
    local remote="$2"
    local cache_dir=$(find_cache_dir)

    [ "$name" -a "$remote" ] || \
      error 1 "Please supply the remote name and the remote url to be added to the cache."

    # add_remote_via_temp_dir "$name" "$remote" "$cache_dir"

    ( cd "$cache_dir"
      git remote add "$name" "$remote"
      git fetch "$name" )
}

function add_remote_via_temp_dir {
    # Fetch new Git repository in a temporary directory for speed reasons
    local name="$1"
    local remote="$2"
    local cache_dir="$3"

    temp_dir=$(mktemp -d)
    ( cd $temp_dir
      git init --bare
      git remote add --mirror=fetch "$name" "$remote"
      git fetch --all
    )

    # Copy it into the main cache directory
    ( cd $cache_dir
      git remote add --mirror=fetch "$name" $temp_dir
      git fetch --all
      git remote set-url "$name" "$remote" )

    # Clean-up
    rm -rf $temp_dir
}

function find_remote_url {
    local name="$1"
    [ "$name" ] || \
      error 1 "Please supply the remote name to find the URL for."

    show_remotes |awk '$1 == name { print $2 }' name="$name"
}

function show_remotes {
    local cache_dir=$(find_cache_dir)

    ( cd "$cache_dir"
      git remote -v |awk '/(fetch)/ { print $1, $2 }' )
}

##########
## MAIN
#########

command="$1"; shift
case $command in
    init)
        create_cache "$1"
        exit
        ;;

    help|-help|--help|-h)
        echo
        echo "Use:"
        echo
        echo "    git cache init [DIR]              initialise the cache directory"
        echo "    git cache delete --force          delete the cache directory"
        echo
        echo "    git cache remote add NAME URL     add a cached Git repository"
        echo "    git cache remote rm --force NAME  remove a cached Git repository"
        echo "    git cache show [NAME]             show all cached Git repositories"
        echo "    git cache update                  fetch all cached Git repository"
        echo "    git cache clone NAME [DIR]        clone a cached repository into a dir"
        echo
        echo "    (Any other command will be applied to the cache directory.)"
        echo "     e.g. 'git cache gc' or 'git cache remote show'.)"
        echo
        echo "Standard cache directory is either:"
        echo
        echo "    /var/cache/git-cache  if created by root (then usable by every user)"
        echo "    ~/.cache/git-cache    else"
        echo
        echo "Once created, the cache directory is written in the configuration parameter"
        echo "'cache.directory', either in the system or global user configuration."
        echo
        exit
        ;;
esac

# If you're using a system cache, you need to not block the others in the group:
set_umask

case "$command" in
    delete)
        [ "$1" = "--force" ] || \
          error 1 "Please supply the --force option to confirm you want to delete the whole cache directory."
        delete_cache
        ;;

    clone)
        clone_referring_cache "$@"
        ;;

    fetch|update)
        update_cached_repos
        ;;

    show)
        if [ "$1" ]; then
          show_clone_command "$1"

        else
            show_remotes
        fi
        ;;

    remote)
        remote_command="$1"; shift
        case "$remote_command" in
            rm|del|delete)
                [ "$1" = "--force" ] || \
                  error 1 "Please supply the --force option to confirm you want to delete this Git repository from the cache directory."
                rm_remote "$2"
                ;;

            add)
                add_remote "$1" "$2"
                ;;

            show)
                show_remotes
                ;;

            *)
                ( cd "$(find_cache_dir)"
                  case "$remote_command" in
                      "")
                          show_remotes
                          ;;

                      *)
                          git remote "$remote_command" "$@"
                          ;;
                  esac )
                ;;
        esac
        ;;

    *)
        # Default trigger to directly act on the cache directory

        ( cd "$(find_cache_dir)"
          case "$command" in
              "")
                  $0 show
                  ;;
              *)
                  git "$command" "$@"
                  ;;
          esac )
        ;;
esac
